#!/usr/bin/env bash
# Fill FORGEJO_SECRET_KEY and FORGEJO_INTERNAL_TOKEN in .env.
#
#   sudo ./scripts/gen-secrets.sh
#
# These two are generated by Forgejo's own generator rather than `openssl rand`:
# INTERNAL_TOKEN is a signed JWT, not a free-form random string, and Forgejo
# will reject an arbitrary value. Secrets are piped straight into .env and are
# never echoed to the terminal or into any log.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$REPO_ROOT/.env"
[ -f "$ENV_FILE" ] || { echo "no .env; copy .env.example first" >&2; exit 1; }

. "$ENV_FILE"
: "${FORGEJO_VERSION:?}"
IMAGE="codeberg.org/forgejo/forgejo:${FORGEJO_VERSION}"

umask 077
say() { printf '\n\033[1;34m==> %s\033[0m\n' "$*"; }

say "Pulling $IMAGE"
docker pull -q "$IMAGE"

gen() {
  docker run --rm "$IMAGE" forgejo generate secret "$1"
}

# Replace in place via a temp file so a failure cannot leave .env truncated.
TMP="$(mktemp "${ENV_FILE}.XXXXXX")"
chmod 600 "$TMP"
cp "$ENV_FILE" "$TMP"

for key in SECRET_KEY INTERNAL_TOKEN; do
  var="FORGEJO_${key}"
  current="$(grep -E "^${var}=" "$ENV_FILE" | head -1 | cut -d= -f2-)"
  case "$current" in
    ""|REPLACE_ME*)
      say "Generating $var"
      value="$(gen "$key")"
      # Written with awk so the value never appears in an argument list that
      # would be visible in `ps` output.
      VALUE="$value" awk -v v="$var" '
        BEGIN { val = ENVIRON["VALUE"] }
        $0 ~ "^" v "=" { print v "=" val; next }
        { print }
      ' "$TMP" > "$TMP.new" && mv "$TMP.new" "$TMP"
      chmod 600 "$TMP"
      unset value
      echo "  $var set (length $(grep -E "^${var}=" "$TMP" | cut -d= -f2- | wc -c) chars, value not shown)"
      ;;
    *)
      echo "  $var already set; leaving it alone"
      echo "  (changing SECRET_KEY on a running instance makes existing 2FA"
      echo "   secrets and stored credentials undecryptable)"
      ;;
  esac
done

mv "$TMP" "$ENV_FILE"
chmod 600 "$ENV_FILE"
# This script runs as root, so the temp file it wrote is root-owned. Hand the
# file back to whoever owns the repo: `docker compose` and the pre-commit hook
# both run unprivileged and must be able to read it. Without this, compose
# cannot interpolate and the hook's local-value scan silently stops working.
if [ -n "${SUDO_USER:-}" ]; then
  chown "$SUDO_USER":"$(id -gn "$SUDO_USER")" "$ENV_FILE"
fi

say "Done"
ls -l "$ENV_FILE"
echo
echo "Reminder: RESTIC_PASSWORD in this file must ALSO be stored in a password"
echo "manager off this machine. It is the one secret whose loss makes every"
echo "backup permanently unrecoverable."
